# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html

deploy_production:
  variables:
    REMOTE_HOST: "195.179.193.31"
    PROJECT_ROOT: "/var/www/site"
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH" | base64 -d)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@${REMOTE_HOST} "cd ${PROJECT_ROOT};git fetch;git checkout origin/master -f;cd ..;sh install.sh -p;docker compose up --detach --build site_app"
  only:
    refs:
      - master

deploy_pages:
  image: node:16
  cache:
    paths:
      - node_modules/
  before_script:
    - npm install
  stage: deploy
  script:
    - mkdir .public
    - npm run build
    - cp -r ./dist/* .public
    - rm -rf public
    - mv .public public
  artifacts:
    paths:
      - public
  only:
    refs:
      - pages
