# This file is a template, and might need editing before it works on your project.
# To contribute improvements to CI/CD templates, please follow the Development guide at:
# https://docs.gitlab.com/ee/development/cicd/templates.html
# This specific template is located at:
# https://gitlab.com/gitlab-org/gitlab/-/blob/master/lib/gitlab/ci/templates/Pages/HTML.gitlab-ci.yml

# Full project: https://gitlab.com/pages/plain-html

stages:
  - build
  - deploy

production_build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
    - mv Dockerfile.production Dockerfile
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - master

production_deploy:
  stage: deploy
  variables:
    REMOTE_HOST: "195.179.193.31"
    PROJECT_ROOT: "/var/www"
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH" | base64 -d)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@${REMOTE_HOST} "cd ${PROJECT_ROOT};./circledwords -p -y"
  only:
    - master

staging_build:
  image: docker:20.10.16
  services:
    - docker:20.10.16-dind
  stage: build
  variables:
    IMAGE_TAG: $CI_REGISTRY_IMAGE:staging-latest
  before_script:
    - apk update && apk add rsync
  script:
    - mv Dockerfile.production Dockerfile
    - rsync .staging/ .
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $IMAGE_TAG .
    - docker push $IMAGE_TAG
  only:
    - develop

staging_deploy:
  stage: deploy
  variables:
    REMOTE_HOST: "195.179.193.31"
    PROJECT_ROOT: "/var/www"
  before_script:
    - "which ssh-agent || ( apt-get update -y && apt-get install openssh-client git -y )"
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$PROD_SSH" | base64 -d)
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - ssh-keyscan ${REMOTE_HOST} >> ~/.ssh/known_hosts
    - chmod 644 ~/.ssh/known_hosts
  script:
    - ssh root@${REMOTE_HOST} "cd ${PROJECT_ROOT};./circledwords -p -y"
  only:
    - develop
